### ISSUE TITLE
Fullstack web courses to be completed. 

### ISSUE THREAD

**Issue by jrforbes24** [urock24/TreehouseProjects#2]
## TODO

_Fullstack courses to be completed._
- [ ] Using jQuery Plugins
- [ ] The Module Pattern in JavaScript
- [ ] Node.js Basics
- [ ] Building a Simple Dynamic Site with Node.js
- [ ] npm Basics
- [ ] using npm as a Task Runner
- [ ]  Express Basics
- [ ] gulp Basics
- [ ] Angular Basics
- [ ] Mongo Basics
- [ ] Building a Mean Application
- [ ] JavaScript Unit Testing

:tada: 

@urock24
